use crate::libkagami::complex::overrides::ASSOverride;

pub fn stringify_override(ov: &ASSOverride) -> String {
    match ov {
        ASSOverride::Bold(v)              => format!("b{}", *v as u8),
        ASSOverride::Italic(v)            => format!("i{}", *v as u8),
        ASSOverride::Underline(v)         => format!("u{}", *v as u8),
        ASSOverride::Strikeout(v)         => format!("s{}", *v as u8),
        ASSOverride::Bord(v)              => format!("bord{v}"),
        ASSOverride::Shad(v)              => format!("shad{v}"),
        ASSOverride::Fn(v)                => format!("fn{v}"),
        ASSOverride::Fs(v)                => format!("fs{v}"),
        ASSOverride::Fsp(v)               => format!("fsp{v}"),
        ASSOverride::Blur(v)              => format!("blur{v}"),
        ASSOverride::Be(v)                => format!("be{v}"),
        ASSOverride::Fscx(v)              => format!("fscx{v}"),
        ASSOverride::Fscy(v)              => format!("fscy{v}"),
        ASSOverride::Fsc(v)               => format!("fsc{v}"),
        ASSOverride::Xbord(v)             => format!("xbord{v}"),
        ASSOverride::Ybord(v)             => format!("ybord{v}"),
        ASSOverride::Xshad(v)             => format!("xshad{v}"),
        ASSOverride::Yshad(v)             => format!("yshad{v}"),
        ASSOverride::Fax(v)               => format!("fax{v}"),
        ASSOverride::Fay(v)               => format!("fay{v}"),
        ASSOverride::Frx(v)               => format!("frx{v}"),
        ASSOverride::Fry(v)               => format!("fry{v}"),
        ASSOverride::Frz(v)               => format!("frz{v}"),
        ASSOverride::Fr(v)                => format!("fr{v}"),
        ASSOverride::Fad(a, b)            => format!("fad({a},{b})"),
        ASSOverride::Fade(a,b,c,d,e,f,g)  => format!("fade({a},{b},{c},{d},{e},{f},{g})"),
        ASSOverride::Pos(x, y)            => format!("pos({x},{y})"),
        ASSOverride::Alpha(v)             => format!("alpha&H{v:02X}&"),
        ASSOverride::AlphaI(v)            => format!("1a&H{v:02X}&"),
        ASSOverride::AlphaII(v)           => format!("2a&H{v:02X}&"),
        ASSOverride::AlphaIII(v)          => format!("3a&H{v:02X}&"),
        ASSOverride::AlphaIV(v)           => format!("4a&H{v:02X}&"),
        ASSOverride::ColorI(v)            => format!("c&H{v:06X}&"),
        ASSOverride::ColorII(v)           => format!("2c&H{v:06X}&"),
        ASSOverride::ColorIII(v)          => format!("3c&H{v:06X}&"),
        ASSOverride::ColorIV(v)           => format!("4c&H{v:06X}&"),
        ASSOverride::An(v)                => format!("an{v}"),
        ASSOverride::P(v)                 => format!("p{v}"),
        ASSOverride::ClipI(v)             => format!("clip({v})"),
        ASSOverride::ClipII(s, v)         => format!("clip({s},{v})"),
        ASSOverride::IclipI(v)            => format!("iclip({v})"),
        ASSOverride::IclipII(s, v)        => format!("iclip({s},{v})"),
        ASSOverride::TransformI(v)        => format!("t({})", stringify_overrides(v)),
        ASSOverride::TransformII(a, v)    => format!("t({a},{})", stringify_overrides(v)),
        ASSOverride::TransformIII(a,b,v)  => format!("t({a},{b},{})", stringify_overrides(v)),
        ASSOverride::TransformIV(a,b,c,v) => format!("t({a},{b},{c},{})", stringify_overrides(v)),
        ASSOverride::Fe(v)                => format!("fe{v}"),
        ASSOverride::MoveI(a,b,c,d)       => format!("move({a},{b},{c},{d})"),
        ASSOverride::MoveII(a,b,c,d,e,f)  => format!("move({a},{b},{c},{d},{e},{f})"),
        ASSOverride::Org(x,y)             => format!("org({x},{y})"),
        ASSOverride::Pbo(v)               => format!("pbo{v}"),
        ASSOverride::Q(v)                 => format!("q{v}"),
        ASSOverride::R(None)              => "r".to_string(),
        ASSOverride::R(Some(s))           => format!("r{s}"),
        ASSOverride::K(v)                 => format!("k{v}"),
        ASSOverride::KSweep(v)            => format!("K{v}"),
        ASSOverride::Kf(v)                => format!("kf{v}"),
        ASSOverride::Ko(v)                => format!("ko{v}"),
    }
}

pub fn stringify_overrides(v: &[ASSOverride]) -> String {
    v.iter()
        .map(|o| format!("\\{}", stringify_override(o)))
        .collect::<Vec<_>>()
        .join("")
}

/// Debug formatter for tests — human readable variant names with values
pub fn fmt_override(ov: &ASSOverride) -> String {
    match ov {
        ASSOverride::Bold(v)              => format!("Bold({v})"),
        ASSOverride::Italic(v)            => format!("Italic({v})"),
        ASSOverride::Underline(v)         => format!("Underline({v})"),
        ASSOverride::Strikeout(v)         => format!("Strikeout({v})"),
        ASSOverride::Bord(v)              => format!("Bord({v})"),
        ASSOverride::Shad(v)              => format!("Shad({v})"),
        ASSOverride::Fn(v)                => format!("Fn({v:?})"),
        ASSOverride::Fs(v)                => format!("Fs({v})"),
        ASSOverride::Fsp(v)               => format!("Fsp({v})"),
        ASSOverride::Blur(v)              => format!("Blur({v})"),
        ASSOverride::Be(v)                => format!("Be({v})"),
        ASSOverride::Fscx(v)              => format!("Fscx({v})"),
        ASSOverride::Fscy(v)              => format!("Fscy({v})"),
        ASSOverride::Fsc(v)               => format!("Fsc({v})"),
        ASSOverride::Xbord(v)             => format!("Xbord({v})"),
        ASSOverride::Ybord(v)             => format!("Ybord({v})"),
        ASSOverride::Xshad(v)             => format!("Xshad({v})"),
        ASSOverride::Yshad(v)             => format!("Yshad({v})"),
        ASSOverride::Fax(v)               => format!("Fax({v})"),
        ASSOverride::Fay(v)               => format!("Fay({v})"),
        ASSOverride::Fr(v)                => format!("Fr({v})"),
        ASSOverride::Frx(v)               => format!("Frx({v})"),
        ASSOverride::Fry(v)               => format!("Fry({v})"),
        ASSOverride::Frz(v)               => format!("Frz({v})"),
        ASSOverride::Fad(a, b)            => format!("Fad({a}, {b})"),
        ASSOverride::Fade(a,b,c,d,e,f,g)  => format!("Fade({a},{b},{c},{d},{e},{f},{g})"),
        ASSOverride::Pos(x, y)            => format!("Pos({x}, {y})"),
        ASSOverride::Alpha(v)             => format!("Alpha({v:#010X})"),
        ASSOverride::AlphaI(v)            => format!("AlphaI({v:#010X})"),
        ASSOverride::AlphaII(v)           => format!("AlphaII({v:#010X})"),
        ASSOverride::AlphaIII(v)          => format!("AlphaIII({v:#010X})"),
        ASSOverride::AlphaIV(v)           => format!("AlphaIV({v:#010X})"),
        ASSOverride::ColorI(v)            => format!("ColorI({v:#010X})"),
        ASSOverride::ColorII(v)           => format!("ColorII({v:#010X})"),
        ASSOverride::ColorIII(v)          => format!("ColorIII({v:#010X})"),
        ASSOverride::ColorIV(v)           => format!("ColorIV({v:#010X})"),
        ASSOverride::An(v)                => format!("An({v})"),
        ASSOverride::P(v)                 => format!("P({v})"),
        ASSOverride::ClipI(v)             => format!("ClipI({v:?})"),
        ASSOverride::ClipII(s, v)         => format!("ClipII({s}, {v:?})"),
        ASSOverride::IclipI(v)            => format!("IclipI({v:?})"),
        ASSOverride::IclipII(s, v)        => format!("IclipII({s}, {v:?})"),
        ASSOverride::TransformI(v)        => format!("TransformI([{}])", fmt_overrides(v)),
        ASSOverride::TransformII(a, v)    => format!("TransformII({a}, [{}])", fmt_overrides(v)),
        ASSOverride::TransformIII(a,b,v)  => format!("TransformIII({a}, {b}, [{}])", fmt_overrides(v)),
        ASSOverride::TransformIV(a,b,c,v) => format!("TransformIV({a}, {b}, {c}, [{}])", fmt_overrides(v)),
        ASSOverride::Fe(v)                => format!("Fe({v})"),
        ASSOverride::MoveI(a,b,c,d)       => format!("MoveI({a},{b},{c},{d})"),
        ASSOverride::MoveII(a,b,c,d,e,f)  => format!("MoveII({a},{b},{c},{d},{e},{f})"),
        ASSOverride::Org(x,y)             => format!("Org({x},{y})"),
        ASSOverride::Pbo(v)               => format!("Pbo({v})"),
        ASSOverride::Q(v)                 => format!("Q({v})"),
        ASSOverride::R(v)                 => format!("R({v:?})"),
        ASSOverride::K(v)                 => format!("K({v})"),
        ASSOverride::KSweep(v)            => format!("KSweep({v})"),
        ASSOverride::Kf(v)                => format!("Kf({v})"),
        ASSOverride::Ko(v)                => format!("Ko({v})"),
    }
}

pub fn fmt_overrides(v: &[ASSOverride]) -> String {
    v.iter().map(fmt_override).collect::<Vec<_>>().join(", ")
}