use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use crate::libkagami::complex::overrides::ASSOverride;
use crate::libkagami::drawing::parse::Drawing;
use crate::libkagami::tags::{ASSLine, ASSText};
use crate::libkagami::complex::types::{AssColour, AssTime};
use tokio::{fs::File, io::{AsyncReadExt, AsyncWriteExt}};

pub struct ScriptInfo {
    pub title: String,
    pub script_type: String,
    pub wrap_style: u8,
    pub scaled_border_and_shadow: bool,
    pub playresx: u16,
    pub playresy: u16,
    pub ycbcr_matrix: String,
    pub layout_res_x: u16,
    pub layout_res_y: u16,
}

impl ScriptInfo {
    pub fn stringify(&self) -> String {
        let mut stringified = String::new();
        let xv = vec![
            /*format!("; Script generated by libkagami\n"),
            format!("; github/evilja discord/myishap\n"),*/
            format!("Title: {}\n", self.title),
            format!("ScriptType: {}\n", self.script_type),
            format!("WrapStyle: {}\n", self.wrap_style),
            format!("ScaledBorderAndShadow: {}\n", match self.scaled_border_and_shadow { true => "Yes", false => "No" }),
            format!("PlayResX: {}\n", self.playresx),
            format!("PlayResY: {}\n", self.playresy),
            format!("YCbCr Matrix: {}\n", self.ycbcr_matrix),
            format!("LayoutResX: {}\n", self.layout_res_x),
            format!("LayoutResY: {}\n", self.layout_res_y),
        ];
        for i in xv {
            stringified.push_str(&i);
        }
        stringified
    }
}

pub struct V4pStyle {
    pub name: String,
    pub fontname: String,
    pub fontsize: u16,
    pub colours: [AssColour; 4],
    pub bold: bool,
    pub italic: bool,
    pub underline: bool,
    pub strikeout: bool,
    pub scale_x: u16,       // percentage, 100 = normal
    pub scale_y: u16,       // percentage, 100 = normal
    pub spacing: f32,       // can be fractional
    pub angle: f32,         // degrees, can be fractional
    pub border_style: u8,   // 1 = outline+shadow, 3 = opaque box
    pub outline: f32,       // pixels, fractional (3.75 in your example)
    pub shadow: f32,        // pixels, fractional
    pub alignment: u8,      // numpad layout 1-9
    pub margin_l: u16,
    pub margin_r: u16,
    pub margin_v: u16,
    pub encoding: u8,
}
// Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
// Style: Default,Arial,60,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3.75,0,2,50,50,38,1
impl V4pStyle {
    pub fn stringify(&self) -> String {
        format!("Style: {},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}\n",
            self.name, self.fontname, self.fontsize, self.colours[0], self.colours[1], self.colours[2], self.colours[3],
            if self.bold { "-1" } else { "0" }, if self.italic { "-1" } else { "0" }, if self.underline { "-1" } else { "0" },
            if self.strikeout { "-1" } else { "0" }, self.scale_x, self.scale_y, self.spacing, self.angle, self.border_style, self.outline,
            self.shadow, self.alignment, self.margin_l, self.margin_r, self.margin_v, self.encoding,
        )
    }
    pub fn to_overrides(&self) -> Vec<ASSOverride> {
        vec![
            ASSOverride::Bold(self.bold),
            ASSOverride::Italic(self.italic),
            ASSOverride::Underline(self.underline),
            ASSOverride::Strikeout(self.strikeout),
            ASSOverride::Fs(self.fontsize as f32),
            ASSOverride::Fscx(self.scale_x as f32),
            ASSOverride::Fscy(self.scale_y as f32),
            ASSOverride::Fsp(self.spacing),
            ASSOverride::Frz(self.angle),
            ASSOverride::Bord(self.outline),
            ASSOverride::Shad(self.shadow),
            ASSOverride::An(self.alignment),
            ASSOverride::ColorI(self.colours[0].as_u32()),
            ASSOverride::ColorII(self.colours[1].as_u32()),
            ASSOverride::ColorIII(self.colours[2].as_u32()),
            ASSOverride::ColorIV(self.colours[3].as_u32()),
            ASSOverride::Fn(self.fontname.clone()),
        ]
    }
}

#[derive(Clone)]
pub struct Event {
    pub layer: u16,
    pub start: AssTime,
    pub end: AssTime,
    pub style: String,      // references V4pStyle by name
    pub name: String,       // actor/speaker field
    pub margin_l: u16,      // 0 = style default
    pub margin_r: u16,
    pub margin_v: u16,
    pub effect: String,     // kfx
    pub text: ASSLine,      // raw text including override tags
}

impl Event {
    pub fn stringify(&self) -> String {
        format!("Dialogue: {},{},{},{},{},{},{},{},{},{}\n",
            self.layer, self.start, self.end, self.style, self.name,
            self.margin_l, self.margin_r, self.margin_v, self.effect,
            self.text.stringify(),
        )
    }

    pub fn raw_text(&self) -> String {
        self.text
            .data
            .iter()
            .filter_map(|item| match item {
                ASSText::RawText(text) => Some(text.as_str()),
                _ => None,
            })
            .collect()
    }

    pub fn is_stamp(&self) -> bool {
        self.name.trim().eq_ignore_ascii_case("stamp")
            || self.effect.trim().eq_ignore_ascii_case("stamp")
    }

    pub fn has_fn(&self) -> bool {
        self.text.has_fn()
    }

    pub fn has_drawing(&self) -> bool {
        self.text.has_drawing()
    }

    pub fn tag_count(&self) -> usize {
        self.text.tag_count()
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PandoraMeta {
    pub stamps: Vec<Stamp>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Stamp {
    pub start: AssTime,
    pub end: AssTime,
    pub note: String,
}

pub struct SubstationAlpha {
    pub script_info: ScriptInfo,
    pub v4p_styles: Vec<V4pStyle>,
    pub events: Vec<Event>,
    pub comments: Vec<Event>,
    pub pandora_meta: PandoraMeta,
}

impl SubstationAlpha {
    pub fn scale(&mut self, target_x: u16, target_y: u16) -> Result<(), String> {
        let source_x = self.script_info.playresx;
        let source_y = self.script_info.playresy;
        if source_x == 0 || source_y == 0 {
            return Err("source PlayRes must be non-zero".to_string());
        }
        if target_x == 0 || target_y == 0 {
            return Err("target PlayRes must be non-zero".to_string());
        }
        if source_x as u32 * target_y as u32 != source_y as u32 * target_x as u32 {
            return Err(format!(
                "incompatible aspect ratio: {}x{} cannot scale to {}x{}",
                source_x, source_y, target_x, target_y
            ));
        }

        let sx = target_x as f32 / source_x as f32;
        let sy = target_y as f32 / source_y as f32;
        let layout_sx = sx;
        let layout_sy = sy;

        self.script_info.playresx = target_x;
        self.script_info.playresy = target_y;
        if self.script_info.layout_res_x != 0 {
            self.script_info.layout_res_x = scale_u16(self.script_info.layout_res_x, sx);
        }
        if self.script_info.layout_res_y != 0 {
            self.script_info.layout_res_y = scale_u16(self.script_info.layout_res_y, sy);
        }

        for style in &mut self.v4p_styles {
            style.fontsize = scale_u16(style.fontsize, sy);
            style.spacing *= sx;
            style.outline *= border_scalar(self.script_info.scaled_border_and_shadow, sx, layout_sx);
            style.shadow *= border_scalar(self.script_info.scaled_border_and_shadow, sx, layout_sx);
            style.margin_l = scale_u16(style.margin_l, sx);
            style.margin_r = scale_u16(style.margin_r, sx);
            style.margin_v = scale_u16(style.margin_v, sy);
        }

        for event in &mut self.events {
            event.margin_l = scale_u16(event.margin_l, sx);
            event.margin_r = scale_u16(event.margin_r, sx);
            event.margin_v = scale_u16(event.margin_v, sy);
            event.effect = scale_effect(&event.effect, sx, sy);
            scale_line(&mut event.text, sx, sy, layout_sx, layout_sy, self.script_info.scaled_border_and_shadow);
        }

        Ok(())
    }

    /// Loads an ASS file from path. If adv_parsing is true, lib also parses Override Tags, and optimises no-op ones.
    /// If adv_parsing is false, entire text is an ASSLine vector with a single ASSText::RawText
    pub async fn load(path: PathBuf, adv_parsing: bool) -> Self {
        let mut buf = String::new();
        match File::open(path).await {
            Ok(mut f) => { f.read_to_string(&mut buf).await.unwrap(); }
            Err(_) => unimplemented!("file open err")
        }
        let buf = buf.trim_start_matches('\u{FEFF}');
        let mut title = String::new();
        let mut script_type = String::new();
        let mut wrap_style = 0u8;
        let mut scaled_border_and_shadow = false;
        let mut ycbcr_matrix = String::new();
        let mut playresx = 0u16;
        let mut playresy = 0u16;
        let mut layout_res_x = 0u16;
        let mut layout_res_y = 0u16;
        let mut v4p_styles = Vec::new();
        let mut events = Vec::new();
        let mut comments = Vec::new();
        let mut pandora_meta = PandoraMeta::default();

        let mut section = "";

        for line in buf.lines() {
            let line = line.trim();
            if line.starts_with('[') {
                section = line;
                continue;
            }
            if line.starts_with(';') || line.is_empty() {
                continue;
            }

            match section {
                "[Script Info]" => {
                    if let Some((key, val)) = line.split_once(':') {
                        match key.trim() {
                            "Title" => title = val.trim().to_string(),
                            "ScriptType" => script_type = val.trim().to_string(),
                            "WrapStyle" => wrap_style = val.trim().parse().unwrap_or(0),
                            "ScaledBorderAndShadow" => scaled_border_and_shadow = val.trim().eq_ignore_ascii_case("yes"),
                            "YCbCr Matrix" => ycbcr_matrix = val.trim().to_string(),
                            "PlayResX" => playresx = val.trim().parse().unwrap_or(0),
                            "PlayResY" => playresy = val.trim().parse().unwrap_or(0),
                            "LayoutResX" => layout_res_x = val.trim().parse().unwrap_or(0),
                            "LayoutResY" => layout_res_y = val.trim().parse().unwrap_or(0),
                            _ => {}
                        }
                    }
                }
                "[V4+ Styles]" => {
                    if let Some(data) = line.strip_prefix("Style:") {
                        let f: Vec<&str> = data.trim().splitn(24, ',').collect();
                        if f.len() < 23 { continue; }
                        v4p_styles.push(V4pStyle {
                            name:         f[0].to_string(),
                            fontname:     f[1].to_string(),
                            fontsize:     f[2].parse().unwrap_or(0),
                            colours: [
                                f[3].parse().unwrap_or(AssColour::opaque_white()),
                                f[4].parse().unwrap_or(AssColour::opaque_white()),
                                f[5].parse().unwrap_or(AssColour::transparent()),
                                f[6].parse().unwrap_or(AssColour::transparent()),
                            ],
                            bold:          f[7] == "-1",
                            italic:        f[8] == "-1",
                            underline:     f[9] == "-1",
                            strikeout:     f[10] == "-1",
                            scale_x:       f[11].parse().unwrap_or(100),
                            scale_y:       f[12].parse().unwrap_or(100),
                            spacing:       f[13].parse().unwrap_or(0.0),
                            angle:         f[14].parse().unwrap_or(0.0),
                            border_style:  f[15].parse().unwrap_or(1),
                            outline:       f[16].parse().unwrap_or(0.0),
                            shadow:        f[17].parse().unwrap_or(0.0),
                            alignment:     f[18].parse().unwrap_or(2),
                            margin_l:      f[19].parse().unwrap_or(0),
                            margin_r:      f[20].parse().unwrap_or(0),
                            margin_v:      f[21].parse().unwrap_or(0),
                            encoding:      f[22].parse().unwrap_or(1),
                        });
                    }
                }
                "[Events]" => {
                    if let Some(data) = line.strip_prefix("Dialogue:") {
                        if let Some(event) = parse_event(data, adv_parsing, &v4p_styles) {
                            events.push(event);
                        }
                    } else if let Some(data) = line.strip_prefix("Comment:") {
                        if let Some(event) = parse_event(data, false, &v4p_styles) {
                            comments.push(event);
                        }
                    }
                }
                "[Pandora Meta]" => {
                    if let Some(data) = line.strip_prefix("Stamp:") {
                        let mut fields = data.strip_prefix(' ').unwrap_or(data).splitn(3, ',');
                        let (Some(start), Some(end), Some(note)) =
                            (fields.next(), fields.next(), fields.next())
                        else {
                            continue;
                        };
                        let (Ok(start), Ok(end)) = (start.trim().parse(), end.trim().parse()) else {
                            continue;
                        };
                        pandora_meta.stamps.push(Stamp {
                            start,
                            end,
                            note: note.to_string(),
                        });
                    }
                }
                _ => {}
            }
        }

        pandora_meta.stamps.extend(
            comments.iter().filter(|event| event.is_stamp()).map(|event| Stamp {
                start: event.start,
                end: event.end,
                note: event.raw_text(),
            })
        );
        let mut seen = BTreeSet::new();
        pandora_meta.stamps.retain(|stamp| {
            seen.insert((stamp.start.total_centiseconds(), stamp.end.total_centiseconds()))
        });
        pandora_meta.stamps.sort_by_key(|stamp| stamp.start.total_centiseconds());

        Self {
            script_info: ScriptInfo {
                title,
                script_type,
                wrap_style,
                scaled_border_and_shadow,
                playresx,
                playresy,
                ycbcr_matrix,
                layout_res_x: if layout_res_x == 0 { playresx } else { layout_res_x },
                layout_res_y: if layout_res_y == 0 { playresy } else { layout_res_y },
            },
            v4p_styles,
            events,
            comments,
            pandora_meta,
        }
    }
    pub fn add_style(&mut self, style: V4pStyle) {
        self.v4p_styles.push(style);
    }
    pub fn add_event(&mut self, event: Event) {
        self.events.push(event);
    }
    pub fn font_names(&self) -> Vec<String> {
        let mut out = BTreeSet::new();
        for style in &self.v4p_styles {
            insert_font_name(&mut out, &style.fontname);
        }
        for event in &self.events {
            collect_line_fonts(&event.text, &mut out);
        }
        out.into_iter().collect()
    }
    pub fn stringify(&self) -> String {
        let mut sevent = String::new();
        // Script Info
        sevent.push_str("[Script Info]\n");
        sevent.push_str(&self.script_info.stringify());
        // Styles
        sevent.push_str("\n[V4+ Styles]\n");
        sevent.push_str("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n");
        for i in &self.v4p_styles {
            sevent.push_str(&i.stringify());
        }
        // Events
        sevent.push_str("\n[Events]\n");
        sevent.push_str("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n");
        for i in &self.events {
            sevent.push_str(&i.stringify());
        }
        if !self.pandora_meta.stamps.is_empty() {
            sevent.push_str("\n[Pandora Meta]\n");
            for stamp in &self.pandora_meta.stamps {
                sevent.push_str(&format!(
                    "Stamp: {},{},{}\n",
                    stamp.start, stamp.end, stamp.note
                ));
            }
        }
        sevent
    }

    pub async fn dump_to_file(&self, path: PathBuf) -> Result<(), ()> {
        let mut file = match File::create(path).await {
            Ok(f) => f,
            Err(_) => {
                return Err(())
            }
        };
        let sevent = self.stringify();
        match file.write_all(sevent.as_bytes()).await {
            Ok(_) => return Ok(()),
            Err(_) => return Err(())
        }
    }
}

fn parse_event(data: &str, adv_parsing: bool, v4p_styles: &[V4pStyle]) -> Option<Event> {
    let f: Vec<&str> = data.trim().splitn(10, ',').collect();
    if f.len() < 10 {
        return None;
    }
    let text = if adv_parsing {
        let style_overrides = v4p_styles.iter()
            .find(|s| s.name == f[3])
            .map(|s| s.to_overrides())
            .unwrap_or_default();
        ASSLine::from_str_store(f[9], style_overrides)
    } else {
        ASSLine { current_overrides: vec![], data: vec![ASSText::RawText(f[9].into())] }
    };
    Some(Event {
        layer:    f[0].parse().unwrap_or(0),
        start:    f[1].parse().unwrap_or(AssTime { hours: 0, minutes: 0, seconds: 0, centiseconds: 0 }),
        end:      f[2].parse().unwrap_or(AssTime { hours: 0, minutes: 0, seconds: 0, centiseconds: 0 }),
        style:    f[3].to_string(),
        name:     f[4].to_string(),
        margin_l: f[5].parse().unwrap_or(0),
        margin_r: f[6].parse().unwrap_or(0),
        margin_v: f[7].parse().unwrap_or(0),
        effect:   f[8].to_string(),
        text,
    })
}

fn border_scalar(scaled_border_and_shadow: bool, screen_scale: f32, layout_scale: f32) -> f32 {
    if scaled_border_and_shadow { screen_scale } else { layout_scale }
}

fn scale_u16(v: u16, scale: f32) -> u16 {
    let scaled = (v as f32 * scale).round();
    if !scaled.is_finite() || scaled <= 0.0 {
        0
    } else if scaled >= u16::MAX as f32 {
        u16::MAX
    } else {
        scaled as u16
    }
}

fn scale_line(line: &mut ASSLine, sx: f32, sy: f32, layout_sx: f32, layout_sy: f32, scaled_border_and_shadow: bool) {
    let mut drawing = 0;

    for ov in &mut line.current_overrides {
        scale_override(ov, sx, sy, layout_sx, layout_sy, scaled_border_and_shadow);
    }

    for item in &mut line.data {
        match item {
            ASSText::Override(ov) => {
                scale_override(ov, sx, sy, layout_sx, layout_sy, scaled_border_and_shadow);
                if let ASSOverride::P(v) = ov {
                    drawing = *v;
                }
            }
            ASSText::RawText(text) if drawing > 0 => {
                *text = scale_drawing_text(text, sx, sy);
            }
            ASSText::Drawing(drawing) => {
                drawing.scale(sx, sy);
            }
            ASSText::RawText(_) => {}
        }
    }
}

fn scale_override(ov: &mut ASSOverride, sx: f32, sy: f32, layout_sx: f32, layout_sy: f32, scaled_border_and_shadow: bool) {
    let border_x = border_scalar(scaled_border_and_shadow, sx, layout_sx);
    let border_y = border_scalar(scaled_border_and_shadow, sy, layout_sy);
    match ov {
        ASSOverride::Bord(v) | ASSOverride::Shad(v) => *v *= border_y,
        ASSOverride::Xbord(v) | ASSOverride::Xshad(v) => *v *= border_x,
        ASSOverride::Ybord(v) | ASSOverride::Yshad(v) => *v *= border_y,
        ASSOverride::Fs(v) => *v *= sy,
        ASSOverride::Fsp(v) => *v *= sx,
        ASSOverride::Blur(v) => *v *= layout_y_scalar(layout_sx, layout_sy),
        ASSOverride::Pos(x, y) | ASSOverride::Org(x, y) => {
            *x *= sx;
            *y *= sy;
        }
        ASSOverride::ClipRect(x0, y0, x1, y1) | ASSOverride::IclipRect(x0, y0, x1, y1) => {
            *x0 *= sx;
            *x1 *= sx;
            *y0 *= sy;
            *y1 *= sy;
        }
        ASSOverride::ClipI(d) | ASSOverride::IclipI(d) => {
            *d = scale_drawing_text(d, sx, sy);
        }
        ASSOverride::ClipII(_, d) | ASSOverride::IclipII(_, d) => {
            *d = scale_drawing_text(d, sx, sy);
        }
        ASSOverride::MoveI(x0, y0, x1, y1) => {
            *x0 *= sx;
            *x1 *= sx;
            *y0 *= sy;
            *y1 *= sy;
        }
        ASSOverride::MoveII(x0, y0, x1, y1, _, _) => {
            *x0 *= sx;
            *x1 *= sx;
            *y0 *= sy;
            *y1 *= sy;
        }
        ASSOverride::Pbo(v) => *v *= sy,
        ASSOverride::TransformI(tags) => scale_overrides(tags, sx, sy, layout_sx, layout_sy, scaled_border_and_shadow),
        ASSOverride::TransformII(_, tags) => scale_overrides(tags, sx, sy, layout_sx, layout_sy, scaled_border_and_shadow),
        ASSOverride::TransformIII(_, _, tags) => scale_overrides(tags, sx, sy, layout_sx, layout_sy, scaled_border_and_shadow),
        ASSOverride::TransformIV(_, _, _, tags) => scale_overrides(tags, sx, sy, layout_sx, layout_sy, scaled_border_and_shadow),
        _ => {}
    }
}

fn scale_overrides(tags: &mut [ASSOverride], sx: f32, sy: f32, layout_sx: f32, layout_sy: f32, scaled_border_and_shadow: bool) {
    for tag in tags {
        scale_override(tag, sx, sy, layout_sx, layout_sy, scaled_border_and_shadow);
    }
}

fn layout_y_scalar(layout_sx: f32, layout_sy: f32) -> f32 {
    if (layout_sx - layout_sy).abs() < 0.0001 { layout_sy } else { (layout_sx + layout_sy) / 2.0 }
}

fn scale_drawing_text(s: &str, sx: f32, sy: f32) -> String {
    let mut drawing: Drawing = s.parse().unwrap();
    if drawing.commands.is_empty() {
        s.to_string()
    } else {
        drawing.scale(sx, sy);
        drawing.stringify()
    }
}

fn format_scaled(v: f32) -> String {
    let rounded = v.round();
    if (v - rounded).abs() < 0.0001 {
        format!("{}", rounded as i64)
    } else {
        let mut s = format!("{:.4}", v);
        while s.contains('.') && s.ends_with('0') {
            s.pop();
        }
        if s.ends_with('.') {
            s.pop();
        }
        s
    }
}

fn scale_effect(effect: &str, sx: f32, sy: f32) -> String {
    let mut parts: Vec<String> = effect.split(';').map(|p| p.to_string()).collect();
    let Some(name) = parts.first().map(|p| p.as_str()) else {
        return effect.to_string();
    };

    if name == "Banner" {
        scale_effect_part_inverse(&mut parts, 1, sx);
        scale_effect_part(&mut parts, 3, sx);
    } else if name == "Scroll up" || name == "Scroll down" {
        scale_effect_part(&mut parts, 1, sy);
        scale_effect_part(&mut parts, 2, sy);
        scale_effect_part_inverse(&mut parts, 3, sy);
        scale_effect_part(&mut parts, 4, sy);
    }

    parts.join(";")
}

fn scale_effect_part(parts: &mut [String], index: usize, scale: f32) {
    if let Some(part) = parts.get_mut(index) {
        if let Ok(v) = part.trim().parse::<f32>() {
            *part = format_scaled(v * scale);
        }
    }
}

fn scale_effect_part_inverse(parts: &mut [String], index: usize, scale: f32) {
    if let Some(part) = parts.get_mut(index) {
        if let Ok(v) = part.trim().parse::<f32>() {
            *part = format_scaled(v / scale);
        }
    }
}

pub fn find_system_fonts(names: &[String]) -> Vec<PathBuf> {
    find_fonts_with_roots(names, &[])
}

pub fn find_fonts_with_roots(names: &[String], extra_roots: &[PathBuf]) -> Vec<PathBuf> {
    let wanted: BTreeSet<String> = names.iter()
        .map(|n| normalize_font_name(n))
        .filter(|n| !n.is_empty())
        .collect();
    if wanted.is_empty() {
        return Vec::new();
    }
    let mut found: BTreeSet<PathBuf> = BTreeSet::new();
    let mut font_files = Vec::new();
    for root in extra_roots {
        collect_font_files(root, &mut font_files);
    }
    font_files.extend(system_font_files());
    for path in font_files {
        if cached_normalized_font_names(&path).iter().any(|n| wanted.contains(n)) {
            found.insert(path);
        }
    }
    let mut out: Vec<PathBuf> = found.into_iter().collect();
    out.sort();
    out
}

// Returns the raw font names for a file, cached by mtime and length so
// repeated lookups don't re-read and re-parse every font file on disk. The cache
// is process-local and intentionally has no eviction; entries are only a few
// strings per font file and changed files miss through metadata validation.
pub fn cached_font_names(path: &Path) -> Vec<String> {
    static CACHE: std::sync::OnceLock<
        std::sync::Mutex<std::collections::HashMap<PathBuf, ((std::time::SystemTime, u64), Vec<String>)>>,
    > = std::sync::OnceLock::new();
    let cache = CACHE.get_or_init(|| std::sync::Mutex::new(std::collections::HashMap::new()));

    let key = std::fs::metadata(path)
        .and_then(|m| m.modified().map(|mtime| (mtime, m.len())))
        .ok();

    if let Some(key) = key {
        if let Some((cached_key, names)) = cache.lock().unwrap().get(path) {
            if *cached_key == key {
                return names.clone();
            }
        }
        let names = font_file_names(path).unwrap_or_default();
        cache
            .lock()
            .unwrap()
            .insert(path.to_path_buf(), (key, names.clone()));
        names
    } else {
        font_file_names(path).unwrap_or_default()
    }
}

pub fn cached_normalized_font_names(path: &Path) -> Vec<String> {
    cached_font_names(path)
        .iter()
        .map(|n| normalize_font_name(n))
        .filter(|n| !n.is_empty())
        .collect()
}

fn collect_line_fonts(line: &ASSLine, out: &mut BTreeSet<String>) {
    for item in &line.data {
        match item {
            ASSText::Override(ov) => collect_override_fonts(ov, out),
            ASSText::RawText(s) => collect_raw_fn_fonts(s, out),
            ASSText::Drawing(_) => {}
        }
    }
    for ov in &line.current_overrides {
        collect_override_fonts(ov, out);
    }
}

fn collect_override_fonts(ov: &ASSOverride, out: &mut BTreeSet<String>) {
    match ov {
        ASSOverride::Fn(name) => insert_font_name(out, name),
        ASSOverride::TransformI(items) => collect_override_list_fonts(items, out),
        ASSOverride::TransformII(_, items) => collect_override_list_fonts(items, out),
        ASSOverride::TransformIII(_, _, items) => collect_override_list_fonts(items, out),
        ASSOverride::TransformIV(_, _, _, items) => collect_override_list_fonts(items, out),
        _ => {}
    }
}

fn collect_override_list_fonts(items: &[ASSOverride], out: &mut BTreeSet<String>) {
    for item in items {
        collect_override_fonts(item, out);
    }
}

fn collect_raw_fn_fonts(s: &str, out: &mut BTreeSet<String>) {
    let bytes = s.as_bytes();
    let mut i = 0usize;
    while i + 2 < bytes.len() {
        if bytes[i] == b'\\' && bytes[i + 1] == b'f' && bytes[i + 2] == b'n' {
            let start = i + 3;
            let mut end = start;
            while end < bytes.len() && bytes[end] != b'\\' && bytes[end] != b'}' {
                end += 1;
            }
            insert_font_name(out, &s[start..end]);
            i = end;
        } else {
            i += 1;
        }
    }
}

fn insert_font_name(out: &mut BTreeSet<String>, name: &str) {
    let trimmed = name.trim();
    if !trimmed.is_empty() {
        out.insert(trimmed.to_string());
    }
}

pub fn normalize_font_name(name: &str) -> String {
    name.chars()
        .filter(|c| !c.is_whitespace() && *c != '-' && *c != '_')
        .flat_map(|c| c.to_lowercase())
        .collect()
}

fn system_font_files() -> Vec<PathBuf> {
    let mut roots: Vec<PathBuf> = Vec::new();
    if cfg!(windows) {
        roots.push(PathBuf::from(r"C:\Windows\Fonts"));
        if let Ok(local) = std::env::var("LOCALAPPDATA") {
            roots.push(PathBuf::from(local).join("Microsoft").join("Windows").join("Fonts"));
        }
    } else if cfg!(target_os = "macos") {
        roots.push(PathBuf::from("/System/Library/Fonts"));
        roots.push(PathBuf::from("/Library/Fonts"));
        if let Ok(home) = std::env::var("HOME") {
            roots.push(PathBuf::from(home).join("Library").join("Fonts"));
        }
    } else {
        roots.push(PathBuf::from("/usr/share/fonts"));
        roots.push(PathBuf::from("/usr/local/share/fonts"));
        if let Ok(home) = std::env::var("HOME") {
            roots.push(PathBuf::from(&home).join(".fonts"));
            roots.push(PathBuf::from(home).join(".local").join("share").join("fonts"));
        }
    }
    let mut out = Vec::new();
    for root in roots {
        collect_font_files(&root, &mut out);
    }
    out
}

pub fn collect_font_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_font_files(&path, out);
        } else if path.extension()
            .and_then(|e| e.to_str())
            .map(|e| matches!(e.to_ascii_lowercase().as_str(), "ttf" | "otf" | "ttc"))
            .unwrap_or(false)
        {
            out.push(path);
        }
    }
}

pub fn font_file_names(path: &Path) -> Result<Vec<String>, ()> {
    let data = std::fs::read(path).map_err(|_| ())?;
    let mut offsets = Vec::new();
    if data.get(0..4) == Some(b"ttcf") {
        let count = read_u32(&data, 8).ok_or(())? as usize;
        for i in 0..count {
            if let Some(offset) = read_u32(&data, 12 + i * 4) {
                offsets.push(offset as usize);
            }
        }
    } else {
        offsets.push(0);
    }
    let mut out = Vec::new();
    for offset in offsets {
        out.extend(sfnt_names(&data, offset).unwrap_or_default());
    }
    Ok(out)
}

fn sfnt_names(data: &[u8], base: usize) -> Result<Vec<String>, ()> {
    let num_tables = read_u16(data, base + 4).ok_or(())? as usize;
    let mut name_offset = None;
    for i in 0..num_tables {
        let rec = base + 12 + i * 16;
        if data.get(rec..rec + 4) == Some(b"name") {
            name_offset = read_u32(data, rec + 8).map(|o| base + o as usize);
            break;
        }
    }
    let name_offset = name_offset.ok_or(())?;
    let count = read_u16(data, name_offset + 2).ok_or(())? as usize;
    let string_offset = name_offset + read_u16(data, name_offset + 4).ok_or(())? as usize;
    let mut out = Vec::new();
    for i in 0..count {
        let rec = name_offset + 6 + i * 12;
        let platform = read_u16(data, rec).ok_or(())?;
        let name_id = read_u16(data, rec + 6).ok_or(())?;
        if !matches!(name_id, 1 | 4 | 6 | 16) {
            continue;
        }
        let len = read_u16(data, rec + 8).ok_or(())? as usize;
        let off = read_u16(data, rec + 10).ok_or(())? as usize;
        let start = string_offset + off;
        let raw = match data.get(start..start + len) {
            Some(r) => r,
            None => continue,
        };
        if let Some(s) = decode_name_string(platform, raw) {
            if !s.trim().is_empty() {
                out.push(s.trim().to_string());
            }
        }
    }
    Ok(out)
}

fn decode_name_string(platform: u16, raw: &[u8]) -> Option<String> {
    if platform == 0 || platform == 3 {
        let mut units = Vec::new();
        let mut i = 0usize;
        while i + 1 < raw.len() {
            units.push(u16::from_be_bytes([raw[i], raw[i + 1]]));
            i += 2;
        }
        String::from_utf16(&units).ok()
    } else {
        Some(raw.iter().map(|b| *b as char).collect())
    }
}

fn read_u16(data: &[u8], offset: usize) -> Option<u16> {
    Some(u16::from_be_bytes([*data.get(offset)?, *data.get(offset + 1)?]))
}

fn read_u32(data: &[u8], offset: usize) -> Option<u32> {
    Some(u32::from_be_bytes([
        *data.get(offset)?,
        *data.get(offset + 1)?,
        *data.get(offset + 2)?,
        *data.get(offset + 3)?,
    ]))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs::{File, FileTimes};
    use std::time::{Duration, SystemTime, UNIX_EPOCH};

    fn test_sub(text: &str) -> SubstationAlpha {
        SubstationAlpha {
            script_info: ScriptInfo {
                title: String::new(),
                script_type: "v4.00+".to_string(),
                wrap_style: 2,
                scaled_border_and_shadow: true,
                playresx: 640,
                playresy: 480,
                ycbcr_matrix: "TV.709".to_string(),
                layout_res_x: 640,
                layout_res_y: 480,
            },
            v4p_styles: vec![V4pStyle {
                name: "Default".to_string(),
                fontname: "Arial".to_string(),
                fontsize: 20,
                colours: [
                    AssColour::opaque_white(),
                    AssColour::opaque_white(),
                    AssColour::transparent(),
                    AssColour::transparent(),
                ],
                bold: false,
                italic: false,
                underline: false,
                strikeout: false,
                scale_x: 100,
                scale_y: 100,
                spacing: 1.5,
                angle: 0.0,
                border_style: 1,
                outline: 2.0,
                shadow: 3.0,
                alignment: 2,
                margin_l: 10,
                margin_r: 20,
                margin_v: 30,
                encoding: 1,
            }],
            events: vec![Event {
                layer: 0,
                start: AssTime { hours: 0, minutes: 0, seconds: 0, centiseconds: 0 },
                end: AssTime { hours: 0, minutes: 0, seconds: 1, centiseconds: 0 },
                style: "Default".to_string(),
                name: String::new(),
                margin_l: 5,
                margin_r: 6,
                margin_v: 7,
                effect: String::new(),
                text: text.parse().unwrap(),
            }],
            comments: Vec::new(),
            pandora_meta: PandoraMeta::default(),
        }
    }

    fn temp_ass_path(name: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!(
            "pandora_libkagami_{}_{}_{}.ass",
            std::process::id(),
            nanos,
            name
        ))
    }

    async fn load_ass(name: &str, contents: &str, adv_parsing: bool) -> (SubstationAlpha, PathBuf) {
        let path = temp_ass_path(name);
        std::fs::write(&path, contents).unwrap();
        let sub = SubstationAlpha::load(path.clone(), adv_parsing).await;
        (sub, path)
    }

    fn temp_font_path(name: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!(
            "pandora_libkagami_{}_{}_{}.ttf",
            std::process::id(),
            nanos,
            name
        ))
    }

    fn push_u16(out: &mut Vec<u8>, value: u16) {
        out.extend(value.to_be_bytes());
    }

    fn push_u32(out: &mut Vec<u8>, value: u32) {
        out.extend(value.to_be_bytes());
    }

    fn utf16be(value: &str) -> Vec<u8> {
        let mut out = Vec::new();
        for unit in value.encode_utf16() {
            out.extend(unit.to_be_bytes());
        }
        out
    }

    fn synthetic_font(names: &[&str]) -> Vec<u8> {
        let mut strings = Vec::new();
        let mut records = Vec::new();
        for (idx, name) in names.iter().enumerate() {
            let encoded = utf16be(name);
            let name_id = match idx % 4 {
                0 => 1,
                1 => 4,
                2 => 6,
                _ => 16,
            };
            push_u16(&mut records, 3);
            push_u16(&mut records, 1);
            push_u16(&mut records, 0x409);
            push_u16(&mut records, name_id);
            push_u16(&mut records, encoded.len() as u16);
            push_u16(&mut records, strings.len() as u16);
            strings.extend(encoded);
        }

        let mut name_table = Vec::new();
        push_u16(&mut name_table, 0);
        push_u16(&mut name_table, names.len() as u16);
        push_u16(&mut name_table, (6 + records.len()) as u16);
        name_table.extend(records);
        name_table.extend(strings);

        let mut font = Vec::new();
        push_u32(&mut font, 0x0001_0000);
        push_u16(&mut font, 1);
        push_u16(&mut font, 0);
        push_u16(&mut font, 0);
        push_u16(&mut font, 0);
        font.extend(b"name");
        push_u32(&mut font, 0);
        push_u32(&mut font, 28);
        push_u32(&mut font, name_table.len() as u32);
        font.extend(name_table);
        font
    }

    fn synthetic_ttc(fonts: &[Vec<u8>]) -> Vec<u8> {
        let mut out = Vec::new();
        out.extend(b"ttcf");
        push_u32(&mut out, 0x0001_0000);
        push_u32(&mut out, fonts.len() as u32);
        let mut offset = 12 + (fonts.len() * 4);
        for font in fonts {
            push_u32(&mut out, offset as u32);
            offset += font.len();
        }
        for font in fonts {
            out.extend(font);
        }
        out
    }

    fn set_modified(path: &Path, time: SystemTime) {
        let file = File::open(path).unwrap();
        file.set_times(FileTimes::new().set_modified(time)).unwrap();
    }

    #[test]
    fn scale_rejects_incompatible_ratio() {
        let mut sub = test_sub("text");

        let err = sub.scale(1280, 720).unwrap_err();

        assert!(err.contains("incompatible aspect ratio"));
        assert_eq!(sub.script_info.playresx, 640);
        assert_eq!(sub.script_info.playresy, 480);
    }

    #[test]
    fn scale_updates_script_style_event_and_tags() {
        let mut sub = test_sub(r"{\pos(100,200)\move(10,20,30,40)\clip(0,1,50,60)\bord4\shad2\fs10\fsp1\pbo5}text");

        sub.scale(1280, 960).unwrap();

        assert_eq!(sub.script_info.playresx, 1280);
        assert_eq!(sub.script_info.playresy, 960);
        assert_eq!(sub.script_info.layout_res_x, 1280);
        assert_eq!(sub.script_info.layout_res_y, 960);
        assert_eq!(sub.v4p_styles[0].fontsize, 40);
        assert_eq!(sub.v4p_styles[0].margin_l, 20);
        assert_eq!(sub.v4p_styles[0].margin_r, 40);
        assert_eq!(sub.v4p_styles[0].margin_v, 60);
        assert_eq!(sub.events[0].margin_l, 10);
        assert_eq!(sub.events[0].margin_r, 12);
        assert_eq!(sub.events[0].margin_v, 14);

        let out = sub.events[0].text.stringify();
        assert!(out.contains(r"\pos(200,400)"));
        assert!(out.contains(r"\move(20,40,60,80)"));
        assert!(out.contains(r"\clip(0,2,100,120)"));
        assert!(out.contains(r"\bord8"));
        assert!(out.contains(r"\shad4"));
        assert!(out.contains(r"\fs20"));
        assert!(out.contains(r"\fsp2"));
        assert!(out.contains(r"\pbo10"));
    }

    #[test]
    fn scale_updates_drawings_and_transform_contents() {
        let mut sub = test_sub(r"{\p1}m 10 20 l 30 40{\p0\clip(m 0 0 l 10 10)\t(0,100,\bord2\fs3)}text");

        sub.scale(1280, 960).unwrap();

        let out = sub.events[0].text.stringify();
        assert!(out.contains("m 20 40 l 60 80"));
        assert!(out.contains(r"\clip(m 0 0 l 20 20)"));
        assert!(out.contains(r"\t(0,100,\bord4\fs6)"));
    }

    #[test]
    fn scale_updates_transition_effect_coordinates_and_delay() {
        let mut banner = test_sub("text");
        banner.events[0].effect = "Banner;20;1;30".to_string();

        banner.scale(1280, 960).unwrap();

        assert_eq!(banner.events[0].effect, "Banner;10;1;60");

        let mut scroll = test_sub("text");
        scroll.events[0].effect = "Scroll up;10;100;40;20".to_string();

        scroll.scale(1280, 960).unwrap();

        assert_eq!(scroll.events[0].effect, "Scroll up;20;200;20;40");
    }

    #[tokio::test]
    async fn comments_are_parsed_separately_and_never_stringified() {
        let source = r#"[Script Info]
ScriptType: v4.00+

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,spoken
Comment: 0,0:00:03.00,0:00:04.00,Default,note,0,0,0,,{*garbage}commented
"#;
        let (sub, path) = load_ass("comments", source, true).await;

        assert_eq!(sub.events.len(), 1);
        assert_eq!(sub.comments.len(), 1);
        assert_eq!(sub.comments[0].raw_text(), "{*garbage}commented");
        assert!(matches!(sub.comments[0].text.data.as_slice(), [ASSText::RawText(_)]));
        assert!(!sub.stringify().contains("Comment:"));

        let _ = std::fs::remove_file(path);
    }

    #[tokio::test]
    async fn stamp_match_is_trimmed_case_insensitive_equality() {
        let source = r#"[Events]
Comment: 0,0:00:01.00,0:00:02.00,Default, StAmP ,0,0,0,,actor
Comment: 0,0:00:03.00,0:00:04.00,Default,,0,0,0, stamp ,effect
Comment: 0,0:00:05.00,0:00:06.00,Default,Stamped,0,0,0,,not actor
Comment: 0,0:00:07.00,0:00:08.00,Default,,0,0,0,stampx,not effect
"#;
        let (sub, path) = load_ass("stamp-match", source, false).await;

        assert!(sub.comments[0].is_stamp());
        assert!(sub.comments[1].is_stamp());
        assert!(!sub.comments[2].is_stamp());
        assert!(!sub.comments[3].is_stamp());
        assert_eq!(sub.pandora_meta.stamps.len(), 2);

        let _ = std::fs::remove_file(path);
    }

    #[tokio::test]
    async fn stamp_comments_round_trip_as_pandora_metadata() {
        let source = r#"[Script Info]
ScriptType: v4.00+

[Events]
Comment: 0,0:03:12.00,0:03:15.00,Default,stamp,0,0,0,,first, with comma
Comment: 0,0:01:02.00,0:01:04.00,Default,,0,0,0,STAMP,second
"#;
        let (sub, source_path) = load_ass("stamp-roundtrip-source", source, true).await;
        let expected = sub.pandora_meta.stamps.clone();
        let output = sub.stringify();
        let output_path = temp_ass_path("stamp-roundtrip-output");
        std::fs::write(&output_path, &output).unwrap();
        let reloaded = SubstationAlpha::load(output_path.clone(), true).await;

        assert!(output.contains("[Pandora Meta]"));
        assert!(!output.contains("Comment:"));
        assert_eq!(expected.len(), 2);
        assert_eq!(expected[0].note, "second");
        assert_eq!(expected[1].note, "first, with comma");
        assert_eq!(reloaded.pandora_meta.stamps, expected);
        assert!(reloaded.comments.is_empty());

        let _ = std::fs::remove_file(source_path);
        let _ = std::fs::remove_file(output_path);
    }

    #[tokio::test]
    async fn pandora_metadata_and_comments_merge_without_duplicate_ranges() {
        let source = r#"[Events]
Comment: 0,0:00:10.00,0:00:12.00,Default,stamp,0,0,0,,duplicate comment
Comment: 0,0:00:05.00,0:00:06.00,Default,,0,0,0,stamp,new comment

[Pandora Meta]
Unknown: ignored
Stamp: 0:00:10.00,0:00:12.00,durable note
"#;
        let (sub, path) = load_ass("stamp-merge", source, false).await;

        assert_eq!(sub.pandora_meta.stamps.len(), 2);
        assert_eq!(sub.pandora_meta.stamps[0].start.total_centiseconds(), 500);
        assert_eq!(sub.pandora_meta.stamps[0].note, "new comment");
        assert_eq!(sub.pandora_meta.stamps[1].start.total_centiseconds(), 1_000);
        assert_eq!(sub.pandora_meta.stamps[1].note, "durable note");

        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn cached_normalized_font_names_normalizes_names() {
        let path = temp_font_path("normalize");
        std::fs::write(&path, synthetic_font(&["Gumbo DEMO", "Vesta-Bold"])).unwrap();

        let names = cached_normalized_font_names(&path);

        assert!(names.contains(&"gumbodemo".to_string()));
        assert!(names.contains(&"vestabold".to_string()));
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn cached_normalized_font_names_reads_ttc_collections() {
        let path = temp_font_path("collection");
        let data = synthetic_ttc(&[
            synthetic_font(&["First Font"]),
            synthetic_font(&["Second Font"]),
        ]);
        std::fs::write(&path, data).unwrap();

        let names = cached_normalized_font_names(&path);

        assert!(names.contains(&"firstfont".to_string()));
        assert!(names.contains(&"secondfont".to_string()));
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn cached_normalized_font_names_reuses_same_mtime_and_len() {
        let path = temp_font_path("same-key");
        let mtime = UNIX_EPOCH + Duration::from_secs(1_700_000_000);
        std::fs::write(&path, synthetic_font(&["CacheA"])).unwrap();
        set_modified(&path, mtime);

        assert_eq!(cached_normalized_font_names(&path), vec!["cachea".to_string()]);
        std::fs::write(&path, synthetic_font(&["CacheB"])).unwrap();
        set_modified(&path, mtime);

        assert_eq!(cached_normalized_font_names(&path), vec!["cachea".to_string()]);
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn cached_normalized_font_names_invalidates_same_mtime_changed_len() {
        let path = temp_font_path("changed-len");
        let mtime = UNIX_EPOCH + Duration::from_secs(1_700_000_010);
        std::fs::write(&path, synthetic_font(&["Short"])).unwrap();
        set_modified(&path, mtime);

        assert_eq!(cached_normalized_font_names(&path), vec!["short".to_string()]);
        std::fs::write(&path, synthetic_font(&["Longer Font Name"])).unwrap();
        set_modified(&path, mtime);

        assert_eq!(cached_normalized_font_names(&path), vec!["longerfontname".to_string()]);
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn cached_normalized_font_names_handles_deleted_files() {
        let path = temp_font_path("deleted");
        std::fs::write(&path, synthetic_font(&["Temporary"])).unwrap();
        assert_eq!(cached_normalized_font_names(&path), vec!["temporary".to_string()]);

        std::fs::remove_file(&path).unwrap();

        assert!(cached_normalized_font_names(&path).is_empty());
    }

    #[test]
    fn cached_font_names_returns_raw_names_for_display() {
        let path = temp_font_path("raw-names");
        std::fs::write(&path, synthetic_font(&["Gandhi Sans Bold"])).unwrap();

        assert_eq!(cached_font_names(&path), vec!["Gandhi Sans Bold".to_string()]);
        assert_eq!(
            cached_normalized_font_names(&path),
            vec!["gandhisansbold".to_string()]
        );
        let _ = std::fs::remove_file(path);
    }
}
