use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use crate::libkagami::complex::overrides::ASSOverride;
use crate::libkagami::tags::{ASSLine, ASSText};
use crate::libkagami::complex::types::{AssColour, AssTime};
use tokio::{fs::File, io::{AsyncReadExt, AsyncWriteExt}};

pub struct ScriptInfo {
    pub title: String,
    pub script_type: String,
    pub wrap_style: u8,
    pub scaled_border_and_shadow: bool,
    pub playresx: u16,
    pub playresy: u16,
    pub ycbcr_matrix: String,
    pub layout_res_x: u16,
    pub layout_res_y: u16,
}

impl ScriptInfo {
    pub fn stringify(&self) -> String {
        let mut stringified = String::new();
        let xv = vec![
            /*format!("; Script generated by libkagami\n"),
            format!("; github/evilja discord/myishap\n"),*/
            format!("Title: {}\n", self.title),
            format!("ScriptType: {}\n", self.script_type),
            format!("WrapStyle: {}\n", self.wrap_style),
            format!("ScaledBorderAndShadow: {}\n", match self.scaled_border_and_shadow { true => "Yes", false => "No" }),
            format!("PlayResX: {}\n", self.playresx),
            format!("PlayResY: {}\n", self.playresy),
            format!("YCbCr Matrix: {}\n", self.ycbcr_matrix),
            format!("LayoutResX: {}\n", self.layout_res_x),
            format!("LayoutResY: {}\n", self.layout_res_y),
        ];
        for i in xv {
            stringified.push_str(&i);
        }
        stringified
    }
}

pub struct V4pStyle {
    pub name: String,
    pub fontname: String,
    pub fontsize: u16,
    pub colours: [AssColour; 4],
    pub bold: bool,
    pub italic: bool,
    pub underline: bool,
    pub strikeout: bool,
    pub scale_x: u16,       // percentage, 100 = normal
    pub scale_y: u16,       // percentage, 100 = normal
    pub spacing: f32,       // can be fractional
    pub angle: f32,         // degrees, can be fractional
    pub border_style: u8,   // 1 = outline+shadow, 3 = opaque box
    pub outline: f32,       // pixels, fractional (3.75 in your example)
    pub shadow: f32,        // pixels, fractional
    pub alignment: u8,      // numpad layout 1-9
    pub margin_l: u16,
    pub margin_r: u16,
    pub margin_v: u16,
    pub encoding: u8,
}
// Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
// Style: Default,Arial,60,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3.75,0,2,50,50,38,1
impl V4pStyle {
    pub fn stringify(&self) -> String {
        format!("Style: {},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}\n",
            self.name, self.fontname, self.fontsize, self.colours[0], self.colours[1], self.colours[2], self.colours[3],
            if self.bold { "-1" } else { "0" }, if self.italic { "-1" } else { "0" }, if self.underline { "-1" } else { "0" },
            if self.strikeout { "-1" } else { "0" }, self.scale_x, self.scale_y, self.spacing, self.angle, self.border_style, self.outline,
            self.shadow, self.alignment, self.margin_l, self.margin_r, self.margin_v, self.encoding,
        )
    }
    pub fn to_overrides(&self) -> Vec<ASSOverride> {
        vec![
            ASSOverride::Bold(self.bold),
            ASSOverride::Italic(self.italic),
            ASSOverride::Underline(self.underline),
            ASSOverride::Strikeout(self.strikeout),
            ASSOverride::Fs(self.fontsize as f32),
            ASSOverride::Fscx(self.scale_x as f32),
            ASSOverride::Fscy(self.scale_y as f32),
            ASSOverride::Fsp(self.spacing),
            ASSOverride::Frz(self.angle),
            ASSOverride::Bord(self.outline),
            ASSOverride::Shad(self.shadow),
            ASSOverride::An(self.alignment),
            ASSOverride::ColorI(self.colours[0].as_u32()),
            ASSOverride::ColorII(self.colours[1].as_u32()),
            ASSOverride::ColorIII(self.colours[2].as_u32()),
            ASSOverride::ColorIV(self.colours[3].as_u32()),
            ASSOverride::Fn(self.fontname.clone()),
        ]
    }
}

pub struct Event {
    pub layer: u16,
    pub start: AssTime,
    pub end: AssTime,
    pub style: String,      // references V4pStyle by name
    pub name: String,       // actor/speaker field
    pub margin_l: u16,      // 0 = style default
    pub margin_r: u16,
    pub margin_v: u16,
    pub effect: String,     // kfx
    pub text: ASSLine,      // raw text including override tags
}

impl Event {
    pub fn stringify(&self) -> String {
        format!("Dialogue: {},{},{},{},{},{},{},{},{},{}\n",
            self.layer, self.start, self.end, self.style, self.name,
            self.margin_l, self.margin_r, self.margin_v, self.effect,
            self.text.stringify(),
        )
    }
}


pub struct SubstationAlpha {
    pub script_info: ScriptInfo,
    pub v4p_styles: Vec<V4pStyle>,
    pub events: Vec<Event>,
}

impl SubstationAlpha {
    /// Loads an ASS file from path. If adv_parsing is true, lib also parses Override Tags, and optimises no-op ones.
    /// If adv_parsing is false, entire text is an ASSLine vector with a single ASSText::RawText
    pub async fn load(path: PathBuf, adv_parsing: bool) -> Self {
        let mut buf = String::new();
        match File::open(path).await {
            Ok(mut f) => { f.read_to_string(&mut buf).await.unwrap(); }
            Err(_) => unimplemented!("file open err")
        }
        let buf = buf.trim_start_matches('\u{FEFF}');
        let mut title = String::new();
        let mut script_type = String::new();
        let mut wrap_style = 0u8;
        let mut scaled_border_and_shadow = false;
        let mut ycbcr_matrix = String::new();
        let mut playresx = 0u16;
        let mut playresy = 0u16;
        let mut layout_res_x = 0u16;
        let mut layout_res_y = 0u16;
        let mut v4p_styles = Vec::new();
        let mut events = Vec::new();

        let mut section = "";

        for line in buf.lines() {
            let line = line.trim();
            if line.starts_with('[') {
                section = line;
                continue;
            }
            if line.starts_with(';') || line.is_empty() {
                continue;
            }

            match section {
                "[Script Info]" => {
                    if let Some((key, val)) = line.split_once(':') {
                        match key.trim() {
                            "Title" => title = val.trim().to_string(),
                            "ScriptType" => script_type = val.trim().to_string(),
                            "WrapStyle" => wrap_style = val.trim().parse().unwrap_or(0),
                            "ScaledBorderAndShadow" => scaled_border_and_shadow = val.trim().eq_ignore_ascii_case("yes"),
                            "YCbCr Matrix" => ycbcr_matrix = val.trim().to_string(),
                            "PlayResX" => playresx = val.trim().parse().unwrap_or(0),
                            "PlayResY" => playresy = val.trim().parse().unwrap_or(0),
                            "LayoutResX" => layout_res_x = val.trim().parse().unwrap_or(0),
                            "LayoutResY" => layout_res_y = val.trim().parse().unwrap_or(0),
                            _ => {}
                        }
                    }
                }
                "[V4+ Styles]" => {
                    if let Some(data) = line.strip_prefix("Style:") {
                        let f: Vec<&str> = data.trim().splitn(24, ',').collect();
                        if f.len() < 23 { continue; }
                        v4p_styles.push(V4pStyle {
                            name:         f[0].to_string(),
                            fontname:     f[1].to_string(),
                            fontsize:     f[2].parse().unwrap_or(0),
                            colours: [
                                f[3].parse().unwrap_or(AssColour::opaque_white()),
                                f[4].parse().unwrap_or(AssColour::opaque_white()),
                                f[5].parse().unwrap_or(AssColour::transparent()),
                                f[6].parse().unwrap_or(AssColour::transparent()),
                            ],
                            bold:          f[7] == "-1",
                            italic:        f[8] == "-1",
                            underline:     f[9] == "-1",
                            strikeout:     f[10] == "-1",
                            scale_x:       f[11].parse().unwrap_or(100),
                            scale_y:       f[12].parse().unwrap_or(100),
                            spacing:       f[13].parse().unwrap_or(0.0),
                            angle:         f[14].parse().unwrap_or(0.0),
                            border_style:  f[15].parse().unwrap_or(1),
                            outline:       f[16].parse().unwrap_or(0.0),
                            shadow:        f[17].parse().unwrap_or(0.0),
                            alignment:     f[18].parse().unwrap_or(2),
                            margin_l:      f[19].parse().unwrap_or(0),
                            margin_r:      f[20].parse().unwrap_or(0),
                            margin_v:      f[21].parse().unwrap_or(0),
                            encoding:      f[22].parse().unwrap_or(1),
                        });
                    }
                }
                "[Events]" => {
                    if let Some(data) = line.strip_prefix("Dialogue:") {
                        let f: Vec<&str> = data.trim().splitn(10, ',').collect();
                        if f.len() < 10 { continue; }
                        let text = if adv_parsing {
                            let style_overrides = v4p_styles.iter()
                                .find(|s| s.name == f[3])
                                .map(|s| s.to_overrides())
                                .unwrap_or_default();
                            ASSLine::from_str_store(f[9], style_overrides)
                        } else {
                            ASSLine { current_overrides: vec![], data: vec![ASSText::RawText(f[9].into())] }
                        };
                        events.push(Event {
                            layer:    f[0].parse().unwrap_or(0),
                            start:    f[1].parse().unwrap_or(AssTime { hours: 0, minutes: 0, seconds: 0, centiseconds: 0 }),
                            end:      f[2].parse().unwrap_or(AssTime { hours: 0, minutes: 0, seconds: 0, centiseconds: 0 }),
                            style:    f[3].to_string(),
                            name:     f[4].to_string(),
                            margin_l: f[5].parse().unwrap_or(0),
                            margin_r: f[6].parse().unwrap_or(0),
                            margin_v: f[7].parse().unwrap_or(0),
                            effect:   f[8].to_string(),
                            text,
                        });
                    }
                }
                _ => {}
            }
        }

        Self {
            script_info: ScriptInfo {
                title,
                script_type,
                wrap_style,
                scaled_border_and_shadow,
                playresx,
                playresy,
                ycbcr_matrix,
                layout_res_x: if layout_res_x == 0 { playresx } else { layout_res_x },
                layout_res_y: if layout_res_y == 0 { playresy } else { layout_res_y },
            },
            v4p_styles,
            events,
        }
    }
    pub fn add_style(&mut self, style: V4pStyle) {
        self.v4p_styles.push(style);
    }
    pub fn add_event(&mut self, event: Event) {
        self.events.push(event);
    }
    pub fn font_names(&self) -> Vec<String> {
        let mut out = BTreeSet::new();
        for style in &self.v4p_styles {
            insert_font_name(&mut out, &style.fontname);
        }
        for event in &self.events {
            collect_line_fonts(&event.text, &mut out);
        }
        out.into_iter().collect()
    }
    pub async fn dump_to_file(&self, path: PathBuf) -> Result<(), ()> {
        let mut file = match File::create(path).await {
            Ok(f) => f,
            Err(_) => {
                return Err(())
            }
        };
        let mut sevent = String::new();
        // Script Info
        sevent.push_str("[Script Info]\n");
        sevent.push_str(&self.script_info.stringify());
        // Styles
        sevent.push_str("\n[V4+ Styles]\n");
        sevent.push_str("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n");
        for i in &self.v4p_styles {
            sevent.push_str(&i.stringify());
        }
        // Events
        sevent.push_str("\n[Events]\n");
        sevent.push_str("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n");
        for i in &self.events {
            sevent.push_str(&i.stringify());
        }
        match file.write_all(sevent.as_bytes()).await {
            Ok(_) => return Ok(()),
            Err(_) => return Err(())
        }
    }
}

pub fn find_system_fonts(names: &[String]) -> Vec<PathBuf> {
    find_fonts_with_roots(names, &[])
}

pub fn find_fonts_with_roots(names: &[String], extra_roots: &[PathBuf]) -> Vec<PathBuf> {
    let wanted: BTreeSet<String> = names.iter()
        .map(|n| normalize_font_name(n))
        .filter(|n| !n.is_empty())
        .collect();
    if wanted.is_empty() {
        return Vec::new();
    }
    let mut found: BTreeSet<PathBuf> = BTreeSet::new();
    let mut font_files = Vec::new();
    for root in extra_roots {
        collect_font_files(root, &mut font_files);
    }
    font_files.extend(system_font_files());
    for path in font_files {
        let font_names = match font_file_names(&path) {
            Ok(n) => n,
            Err(_) => continue,
        };
        for name in font_names {
            let normalized = normalize_font_name(&name);
            if wanted.contains(&normalized) {
                found.insert(path.clone());
            }
        }
    }
    let mut out: Vec<PathBuf> = found.into_iter().collect();
    out.sort();
    out
}

fn collect_line_fonts(line: &ASSLine, out: &mut BTreeSet<String>) {
    for item in &line.data {
        match item {
            ASSText::Override(ov) => collect_override_fonts(ov, out),
            ASSText::RawText(s) => collect_raw_fn_fonts(s, out),
        }
    }
    for ov in &line.current_overrides {
        collect_override_fonts(ov, out);
    }
}

fn collect_override_fonts(ov: &ASSOverride, out: &mut BTreeSet<String>) {
    match ov {
        ASSOverride::Fn(name) => insert_font_name(out, name),
        ASSOverride::TransformI(items) => collect_override_list_fonts(items, out),
        ASSOverride::TransformII(_, items) => collect_override_list_fonts(items, out),
        ASSOverride::TransformIII(_, _, items) => collect_override_list_fonts(items, out),
        ASSOverride::TransformIV(_, _, _, items) => collect_override_list_fonts(items, out),
        _ => {}
    }
}

fn collect_override_list_fonts(items: &[ASSOverride], out: &mut BTreeSet<String>) {
    for item in items {
        collect_override_fonts(item, out);
    }
}

fn collect_raw_fn_fonts(s: &str, out: &mut BTreeSet<String>) {
    let bytes = s.as_bytes();
    let mut i = 0usize;
    while i + 2 < bytes.len() {
        if bytes[i] == b'\\' && bytes[i + 1] == b'f' && bytes[i + 2] == b'n' {
            let start = i + 3;
            let mut end = start;
            while end < bytes.len() && bytes[end] != b'\\' && bytes[end] != b'}' {
                end += 1;
            }
            insert_font_name(out, &s[start..end]);
            i = end;
        } else {
            i += 1;
        }
    }
}

fn insert_font_name(out: &mut BTreeSet<String>, name: &str) {
    let trimmed = name.trim();
    if !trimmed.is_empty() {
        out.insert(trimmed.to_string());
    }
}

fn normalize_font_name(name: &str) -> String {
    name.chars()
        .filter(|c| !c.is_whitespace() && *c != '-' && *c != '_')
        .flat_map(|c| c.to_lowercase())
        .collect()
}

fn system_font_files() -> Vec<PathBuf> {
    let mut roots: Vec<PathBuf> = Vec::new();
    if cfg!(windows) {
        roots.push(PathBuf::from(r"C:\Windows\Fonts"));
        if let Ok(local) = std::env::var("LOCALAPPDATA") {
            roots.push(PathBuf::from(local).join("Microsoft").join("Windows").join("Fonts"));
        }
    } else if cfg!(target_os = "macos") {
        roots.push(PathBuf::from("/System/Library/Fonts"));
        roots.push(PathBuf::from("/Library/Fonts"));
        if let Ok(home) = std::env::var("HOME") {
            roots.push(PathBuf::from(home).join("Library").join("Fonts"));
        }
    } else {
        roots.push(PathBuf::from("/usr/share/fonts"));
        roots.push(PathBuf::from("/usr/local/share/fonts"));
        if let Ok(home) = std::env::var("HOME") {
            roots.push(PathBuf::from(&home).join(".fonts"));
            roots.push(PathBuf::from(home).join(".local").join("share").join("fonts"));
        }
    }
    let mut out = Vec::new();
    for root in roots {
        collect_font_files(&root, &mut out);
    }
    out
}

fn collect_font_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_font_files(&path, out);
        } else if path.extension()
            .and_then(|e| e.to_str())
            .map(|e| matches!(e.to_ascii_lowercase().as_str(), "ttf" | "otf" | "ttc"))
            .unwrap_or(false)
        {
            out.push(path);
        }
    }
}

fn font_file_names(path: &Path) -> Result<Vec<String>, ()> {
    let data = std::fs::read(path).map_err(|_| ())?;
    let mut offsets = Vec::new();
    if data.get(0..4) == Some(b"ttcf") {
        let count = read_u32(&data, 8).ok_or(())? as usize;
        for i in 0..count {
            if let Some(offset) = read_u32(&data, 12 + i * 4) {
                offsets.push(offset as usize);
            }
        }
    } else {
        offsets.push(0);
    }
    let mut out = Vec::new();
    for offset in offsets {
        out.extend(sfnt_names(&data, offset).unwrap_or_default());
    }
    Ok(out)
}

fn sfnt_names(data: &[u8], base: usize) -> Result<Vec<String>, ()> {
    let num_tables = read_u16(data, base + 4).ok_or(())? as usize;
    let mut name_offset = None;
    for i in 0..num_tables {
        let rec = base + 12 + i * 16;
        if data.get(rec..rec + 4) == Some(b"name") {
            name_offset = read_u32(data, rec + 8).map(|o| base + o as usize);
            break;
        }
    }
    let name_offset = name_offset.ok_or(())?;
    let count = read_u16(data, name_offset + 2).ok_or(())? as usize;
    let string_offset = name_offset + read_u16(data, name_offset + 4).ok_or(())? as usize;
    let mut out = Vec::new();
    for i in 0..count {
        let rec = name_offset + 6 + i * 12;
        let platform = read_u16(data, rec).ok_or(())?;
        let name_id = read_u16(data, rec + 6).ok_or(())?;
        if !matches!(name_id, 1 | 4 | 6 | 16) {
            continue;
        }
        let len = read_u16(data, rec + 8).ok_or(())? as usize;
        let off = read_u16(data, rec + 10).ok_or(())? as usize;
        let start = string_offset + off;
        let raw = match data.get(start..start + len) {
            Some(r) => r,
            None => continue,
        };
        if let Some(s) = decode_name_string(platform, raw) {
            if !s.trim().is_empty() {
                out.push(s.trim().to_string());
            }
        }
    }
    Ok(out)
}

fn decode_name_string(platform: u16, raw: &[u8]) -> Option<String> {
    if platform == 0 || platform == 3 {
        let mut units = Vec::new();
        let mut i = 0usize;
        while i + 1 < raw.len() {
            units.push(u16::from_be_bytes([raw[i], raw[i + 1]]));
            i += 2;
        }
        String::from_utf16(&units).ok()
    } else {
        Some(raw.iter().map(|b| *b as char).collect())
    }
}

fn read_u16(data: &[u8], offset: usize) -> Option<u16> {
    Some(u16::from_be_bytes([*data.get(offset)?, *data.get(offset + 1)?]))
}

fn read_u32(data: &[u8], offset: usize) -> Option<u32> {
    Some(u32::from_be_bytes([
        *data.get(offset)?,
        *data.get(offset + 1)?,
        *data.get(offset + 2)?,
        *data.get(offset + 3)?,
    ]))
}
