use std::path::PathBuf;
use crate::libkagami::complex::overrides::ASSOverride;
use crate::libkagami::tags::{ASSLine, ASSText};
use crate::libkagami::complex::types::{AssColour, AssTime};
use tokio::{fs::File, io::{AsyncReadExt, AsyncWriteExt}};

pub struct ScriptInfo {
    pub title: String,
    pub script_type: String,
    pub wrap_style: u8,
    pub scaled_border_and_shadow: bool,
    pub ycbcr_matrix: String,
    pub playresx: u16,
    pub playresy: u16,
}

impl ScriptInfo {
    pub fn stringify(&self) -> String {
        let mut stringified = String::new();
        let mut xv = vec![
            format!("; Script generated by libkagami\n"),
            format!("; github/evilja discord/myishap\n"),
            format!("Title: {}\n", self.title),
            format!("ScriptType: {}\n", self.script_type),
            format!("WrapStyle: {}\n", self.wrap_style),
            format!("ScaledBorderAndShadow: {}\n", match self.scaled_border_and_shadow { true => "yes", false => "no" }),
            format!("YCbCr Matrix: {}\n", self.ycbcr_matrix),
        ];
        if self.playresx != 0 {
            xv.push(format!("PlayResX: {}\n", self.playresx));
        }
        if self.playresy != 0 {
            xv.push(format!("PlayResY: {}\n", self.playresy));
        }
        for i in xv {
            stringified.push_str(&i);
        }
        stringified
    }
}

pub struct V4pStyle {
    pub name: String,
    pub fontname: String,
    pub fontsize: u16,
    pub colours: [AssColour; 4],
    pub bold: bool,
    pub italic: bool,
    pub underline: bool,
    pub strikeout: bool,
    pub scale_x: u16,       // percentage, 100 = normal
    pub scale_y: u16,       // percentage, 100 = normal
    pub spacing: f32,       // can be fractional
    pub angle: f32,         // degrees, can be fractional
    pub border_style: u8,   // 1 = outline+shadow, 3 = opaque box
    pub outline: f32,       // pixels, fractional (3.75 in your example)
    pub shadow: f32,        // pixels, fractional
    pub alignment: u8,      // numpad layout 1-9
    pub margin_l: u16,
    pub margin_r: u16,
    pub margin_v: u16,
    pub encoding: u8,
}
// Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
// Style: Default,Arial,60,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3.75,0,2,50,50,38,1
impl V4pStyle {
    pub fn stringify(&self) -> String {
        format!("Style: {},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}\n",
            self.name, self.fontname, self.fontsize, self.colours[0], self.colours[1], self.colours[2], self.colours[3],
            if self.bold { "-1" } else { "0" }, if self.italic { "-1" } else { "0" }, if self.underline { "-1" } else { "0" },
            if self.strikeout { "-1" } else { "0" }, self.scale_x, self.scale_y, self.spacing, self.angle, self.border_style, self.outline,
            self.shadow, self.alignment, self.margin_l, self.margin_r, self.margin_v, self.encoding,
        )
    }
    pub fn to_overrides(&self) -> Vec<ASSOverride> {
        vec![
            ASSOverride::Bold(self.bold),
            ASSOverride::Italic(self.italic),
            ASSOverride::Underline(self.underline),
            ASSOverride::Strikeout(self.strikeout),
            ASSOverride::Fs(self.fontsize as f32),
            ASSOverride::Fscx(self.scale_x as f32),
            ASSOverride::Fscy(self.scale_y as f32),
            ASSOverride::Fsp(self.spacing),
            ASSOverride::Frz(self.angle),
            ASSOverride::Bord(self.outline),
            ASSOverride::Shad(self.shadow),
            ASSOverride::An(self.alignment),
            ASSOverride::ColorI(self.colours[0].as_u32()),
            ASSOverride::ColorII(self.colours[1].as_u32()),
            ASSOverride::ColorIII(self.colours[2].as_u32()),
            ASSOverride::ColorIV(self.colours[3].as_u32()),
            ASSOverride::Fn(self.fontname.clone()),
        ]
    }
}

pub struct Event {
    pub layer: u16,
    pub start: AssTime,
    pub end: AssTime,
    pub style: String,      // references V4pStyle by name
    pub name: String,       // actor/speaker field
    pub margin_l: u16,      // 0 = style default
    pub margin_r: u16,
    pub margin_v: u16,
    pub effect: String,     // kfx
    pub text: ASSLine,      // raw text including override tags
}

impl Event {
    pub fn stringify(&self) -> String {
        format!("Dialogue: {},{},{},{},{},{},{},{},{},{}\n",
            self.layer, self.start, self.end, self.style, self.name,
            self.margin_l, self.margin_r, self.margin_v, self.effect,
            self.text.stringify(),
        )
    }
}


pub struct SubstationAlpha {
    pub script_info: ScriptInfo,
    pub v4p_styles: Vec<V4pStyle>,
    pub events: Vec<Event>,
}

impl SubstationAlpha {
    /// Loads an ASS file from path. If adv_parsing is true, lib also parses Override Tags, and optimises no-op ones.
    /// If adv_parsing is false, entire text is an ASSLine vector with a single ASSText::RawText
    pub async fn load(path: PathBuf, adv_parsing: bool) -> Self {
        let mut buf = String::new();
        match File::open(path).await {
            Ok(mut f) => { f.read_to_string(&mut buf).await.unwrap(); }
            Err(_) => unimplemented!("file open err")
        }
        let buf = buf.trim_start_matches('\u{FEFF}');
        let mut title = String::new();
        let mut script_type = String::new();
        let mut wrap_style = 0u8;
        let mut scaled_border_and_shadow = false;
        let mut ycbcr_matrix = String::new();
        let mut playresx = 0u16;
        let mut playresy = 0u16;
        let mut v4p_styles = Vec::new();
        let mut events = Vec::new();

        let mut section = "";

        for line in buf.lines() {
            let line = line.trim();
            if line.starts_with('[') {
                section = line;
                continue;
            }
            if line.starts_with(';') || line.is_empty() {
                continue;
            }

            match section {
                "[Script Info]" => {
                    if let Some((key, val)) = line.split_once(':') {
                        match key.trim() {
                            "Title" => title = val.trim().to_string(),
                            "ScriptType" => script_type = val.trim().to_string(),
                            "WrapStyle" => wrap_style = val.trim().parse().unwrap_or(0),
                            "ScaledBorderAndShadow" => scaled_border_and_shadow = val.trim().eq_ignore_ascii_case("yes"),
                            "YCbCr Matrix" => ycbcr_matrix = val.trim().to_string(),
                            "PlayResX" => playresx = val.trim().parse().unwrap_or(0),
                            "PlayResY" => playresy = val.trim().parse().unwrap_or(0),
                            _ => {}
                        }
                    }
                }
                "[V4+ Styles]" => {
                    if let Some(data) = line.strip_prefix("Style:") {
                        let f: Vec<&str> = data.trim().splitn(24, ',').collect();
                        if f.len() < 23 { continue; }
                        v4p_styles.push(V4pStyle {
                            name:         f[0].to_string(),
                            fontname:     f[1].to_string(),
                            fontsize:     f[2].parse().unwrap_or(0),
                            colours: [
                                f[3].parse().unwrap_or(AssColour::opaque_white()),
                                f[4].parse().unwrap_or(AssColour::opaque_white()),
                                f[5].parse().unwrap_or(AssColour::transparent()),
                                f[6].parse().unwrap_or(AssColour::transparent()),
                            ],
                            bold:          f[7] == "-1",
                            italic:        f[8] == "-1",
                            underline:     f[9] == "-1",
                            strikeout:     f[10] == "-1",
                            scale_x:       f[11].parse().unwrap_or(100),
                            scale_y:       f[12].parse().unwrap_or(100),
                            spacing:       f[13].parse().unwrap_or(0.0),
                            angle:         f[14].parse().unwrap_or(0.0),
                            border_style:  f[15].parse().unwrap_or(1),
                            outline:       f[16].parse().unwrap_or(0.0),
                            shadow:        f[17].parse().unwrap_or(0.0),
                            alignment:     f[18].parse().unwrap_or(2),
                            margin_l:      f[19].parse().unwrap_or(0),
                            margin_r:      f[20].parse().unwrap_or(0),
                            margin_v:      f[21].parse().unwrap_or(0),
                            encoding:      f[22].parse().unwrap_or(1),
                        });
                    }
                }
                "[Events]" => {
                    if let Some(data) = line.strip_prefix("Dialogue:") {
                        let f: Vec<&str> = data.trim().splitn(10, ',').collect();
                        if f.len() < 10 { continue; }
                        let text = if adv_parsing {
                            let style_overrides = v4p_styles.iter()
                                .find(|s| s.name == f[3])
                                .map(|s| s.to_overrides())
                                .unwrap_or_default();
                            ASSLine::from_str_store(f[9], style_overrides)
                        } else {
                            ASSLine { current_overrides: vec![], data: vec![ASSText::RawText(f[9].into())] }
                        };
                        events.push(Event {
                            layer:    f[0].parse().unwrap_or(0),
                            start:    f[1].parse().unwrap_or(AssTime { hours: 0, minutes: 0, seconds: 0, centiseconds: 0 }),
                            end:      f[2].parse().unwrap_or(AssTime { hours: 0, minutes: 0, seconds: 0, centiseconds: 0 }),
                            style:    f[3].to_string(),
                            name:     f[4].to_string(),
                            margin_l: f[5].parse().unwrap_or(0),
                            margin_r: f[6].parse().unwrap_or(0),
                            margin_v: f[7].parse().unwrap_or(0),
                            effect:   f[8].to_string(),
                            text,
                        });
                    }
                }
                _ => {}
            }
        }

        Self {
            script_info: ScriptInfo { title, script_type, wrap_style, scaled_border_and_shadow, ycbcr_matrix, playresx, playresy },
            v4p_styles,
            events,
        }
    }
    pub fn add_style(&mut self, style: V4pStyle) {
        self.v4p_styles.push(style);
    }
    pub fn add_event(&mut self, event: Event) {
        self.events.push(event);
    }
    pub async fn dump_to_file(&self, path: PathBuf) -> Result<(), ()> {
        let mut file = match File::create(path).await {
            Ok(f) => f,
            Err(_) => {
                return Err(())
            }
        };
        let mut sevent = String::new();
        // Script Info
        sevent.push_str("[Script Info]\n");
        sevent.push_str(&self.script_info.stringify());
        // Styles
        sevent.push_str("\n[V4+ Styles]\n");
        sevent.push_str("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n");
        for i in &self.v4p_styles {
            sevent.push_str(&i.stringify());
        }
        // Events
        sevent.push_str("\n[Events]\n");
        sevent.push_str("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n");
        for i in &self.events {
            sevent.push_str(&i.stringify());
        }
        match file.write(sevent.as_bytes()).await {
            Ok(_) => return Ok(()),
            Err(_) => return Err(())
        }
    }
}
